# docker-compose.yml

version: '3.8'
networks:
  default:
    driver: bridge
services:
  ui:
    image: node:12.18.2
    command: npm start
    working_dir: /app
    restart: on-failure
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./public:/app/public
    ports:
      - 3000:3000
  hand-analysis-service:
    container_name: hand-analysis-service
    image: hand-analysis-service:latest
    build: hand_analysis_service/
    restart: on-failure
    volumes:
      - ./hand_analysis_service/app:/app/code/
    ports:
      - 80:80

  redis:
    container_name: redis
    image: redis:latest
    restart: on-failure
    ports:
      - 6379:6379
